FROM node:20-alpine
WORKDIR /app

COPY package.json ./
COPY tsconfig.json vite.config.ts postcss.config.js tailwind.config.js index.html ./
COPY .env ./.env
COPY src ./src

RUN npm i

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
