FROM node:20-alpine as build
WORKDIR /app
COPY package.json ./
COPY tsconfig.json vite.config.ts postcss.config.js tailwind.config.js index.html ./
COPY .env ./.env
COPY src ./src
RUN npm i && npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
